const russianAuthStrings = <String, String>{
  'account.transferTitle': 'Гостевой черновик',
  'account.transferWorkingPreserved': 'Сохранённый черновик перенесён. Новые рабочие правки сохранены в редакторе; перечитай черновик явно, когда решишь их отменить.',
  'account.transfer': 'Перенести в этот аккаунт',
  'account.transferHint': 'На устройстве есть сохранённый гостевой черновик. Его можно перенести в пустой черновик этого аккаунта; после переноса данные будут синхронизироваться с аккаунтом.',
  'account.transferConfirm': 'Перенести сохранённое портфолио и приватные заметки в этот аккаунт? После переноса гостевой черновик станет пустым, а перенесённые данные будут синхронизироваться с аккаунтом.',
  'account.transferSuccess':
      'Черновик перенесён. Открой Builder, чтобы продолжить.',
  'account.transferUnsaved':
      'Сначала сохрани или отмени текущие правки аккаунта.',
  'account.transferConflict': 'Перенос заблокирован: аккаунт уже содержит черновик или перенос ожидает завершения в другом аккаунте. Данные сохранены. После сбоя повтори перенос в исходный аккаунт.',
  'account.signIn': 'Войти',
  'account.register': 'Создать аккаунт',
  'account.resetPassword': 'Восстановить пароль',
  'account.signInDescription': 'Войдите, чтобы открыть свой черновик и синхронизировать сохранённые правки.',
  'account.registerDescription': 'Создайте аккаунт с email и паролем.',
  'account.resetDescription':
      'Укажите email аккаунта для восстановления доступа.',
  'account.email': 'Email',
  'account.emailHint': 'you@example.com',
  'account.password': 'Пароль',
  'account.passwordHint': 'Не менее 6 символов',
  'account.confirmPassword': 'Повторите пароль',
  'account.passwordMismatch': 'Пароли не совпадают',
  'account.google': 'Войти через Google',
  'account.forgotPassword': 'Забыли пароль?',
  'account.backToSignIn': 'Вернуться ко входу',
  'account.sendReset': 'Отправить письмо',
  'account.resetSuccess': 'Если для этого email существует аккаунт, письмо с инструкцией отправлено. Проверьте почту и папку «Спам».',
  'account.guest': 'Продолжить без аккаунта',
  'account.guestNote': 'Гостевой черновик хранится только на этом устройстве и доступен без сети. Для облачной синхронизации войди в аккаунт.',
  'account.localNote': 'Сохранённый черновик синхронизируется с аккаунтом и доступен без сети. Статус синхронизации показан в редакторе; публикация выполняется отдельно.',
  'account.title': 'Аккаунт',
  'account.guestTitle': 'Гостевой режим',
  'account.signedIn': 'Вы вошли в аккаунт',
  'account.signOut': 'Выйти из аккаунта',
  'account.unsavedTitle': 'Есть несохранённые изменения',
  'account.unsavedHint': 'При смене аккаунта несохранённые правки локального черновика будут потеряны. Отмените действие и сохраните черновик, либо продолжите со сбросом правок.',
  'account.discard': 'Продолжить без сохранения',
  'account.cancel': 'Отмена',
  'account.sessionError': 'Не удалось проверить аккаунт. Повторите попытку.',
  'account.sessionRestoring': 'Проверяем аккаунт…',
  'account.error.invalidEmail': 'Укажите корректный email',
  'account.error.weakPassword': 'Пароль должен содержать не менее 6 символов',
  'account.error.invalidCredentials':
      'Не удалось войти. Проверьте email и пароль.',
  'account.error.emailInUse':
      'Этот email уже используется. Войдите или восстановите пароль.',
  'account.error.userDisabled': 'Доступ к аккаунту отключён.',
  'account.error.network':
      'Нет соединения. Проверьте сеть и повторите попытку.',
  'account.error.tooManyRequests':
      'Слишком много попыток. Попробуйте немного позже.',
  'account.error.configuration':
      'Вход пока недоступен. Не удалось подключить сервис аккаунтов.',
  'account.error.unknown': 'Не удалось выполнить действие. Повторите попытку.',
};

const englishAuthStrings = <String, String>{
  'account.transferTitle': 'Guest draft',
  'account.transferWorkingPreserved': 'The saved draft was moved. New working edits remain in the editor; reload the draft explicitly when you choose to discard them.',
  'account.transfer': 'Move to this account',
  'account.transferHint': 'This device has a saved guest draft. You can move it into this account’s empty draft; the moved data will synchronize with this account.',
  'account.transferConfirm': 'Move the saved portfolio and private notes to this account? The guest draft will become empty and the moved data will synchronize with this account.',
  'account.transferSuccess': 'Draft moved. Open Builder to continue.',
  'account.transferUnsaved': 'Save or discard current account changes first.',
  'account.transferConflict': 'Transfer is blocked: this account already has a draft or another account has a pending transfer. Data is preserved. After a failure, retry in the original account.',
  'account.signIn': 'Sign in',
  'account.register': 'Create account',
  'account.resetPassword': 'Reset password',
  'account.signInDescription':
      'Sign in to open your draft and synchronize saved edits.',
  'account.registerDescription':
      'Create an account with your email and password.',
  'account.resetDescription': 'Enter your account email to restore access.',
  'account.email': 'Email',
  'account.emailHint': 'you@example.com',
  'account.password': 'Password',
  'account.passwordHint': 'At least 6 characters',
  'account.confirmPassword': 'Confirm password',
  'account.passwordMismatch': 'Passwords do not match',
  'account.google': 'Sign in with Google',
  'account.forgotPassword': 'Forgot password?',
  'account.backToSignIn': 'Back to sign in',
  'account.sendReset': 'Send reset email',
  'account.resetSuccess': 'If an account exists for this email, reset instructions have been sent. Check your inbox and spam folder.',
  'account.guest': 'Continue without an account',
  'account.guestNote': 'Your guest draft stays on this device and works offline. Sign in to synchronize with your account.',
  'account.localNote': 'Saved drafts synchronize with your account and are available offline. Check synchronization status in the editor; publishing is a separate action.',
  'account.title': 'Account',
  'account.guestTitle': 'Guest mode',
  'account.signedIn': 'You are signed in',
  'account.signOut': 'Sign out',
  'account.unsavedTitle': 'You have unsaved changes',
  'account.unsavedHint': 'Changing accounts will lose unsaved changes to your local draft. Cancel and save your draft first, or continue and discard these changes.',
  'account.discard': 'Continue without saving',
  'account.cancel': 'Cancel',
  'account.sessionError': 'Unable to check your account. Please try again.',
  'account.sessionRestoring': 'Restoring your account…',
  'account.error.invalidEmail': 'Enter a valid email',
  'account.error.weakPassword': 'Password must contain at least 6 characters',
  'account.error.invalidCredentials':
      'Unable to sign in. Check your email and password.',
  'account.error.emailInUse':
      'This email is already in use. Sign in or reset your password.',
  'account.error.userDisabled': 'This account has been disabled.',
  'account.error.network': 'No connection. Check your network and try again.',
  'account.error.tooManyRequests': 'Too many attempts. Please try again later.',
  'account.error.configuration':
      'Sign-in is unavailable. The account service could not be connected.',
  'account.error.unknown': 'Unable to complete this action. Please try again.',
};
