const builderFormRussianStrings = <String, String>{
  'builderForm.profileTitle': 'Редактировать профиль',
  'builderForm.skillsTitle': 'Навыки',
  'builderForm.experienceTitle': 'Опыт работы',
  'builderForm.educationTitle': 'Образование',
  'builderForm.linksTitle': 'Ссылки',
  'builderForm.resumeTitle': 'Текст резюме',
  'builderForm.newProjectTitle': 'Новый ручной проект',
  'builderForm.editProjectTitle': 'Редактировать проект',
  'builderForm.applyHint': 'Примените изменения к черновику, затем сохраните его на устройстве в Builder.',
  'builderForm.apply': 'Применить',
  'builderForm.cancel': 'Отмена',
  'builderForm.add': 'Добавить',
  'builderForm.addOrUpdate': 'Готово',
  'builderForm.edit': 'Редактировать',
  'builderForm.delete': 'Удалить',
  'builderForm.name': 'Имя',
  'builderForm.username': 'Username',
  'builderForm.usernameHint':
      '3–30 символов: строчные латинские буквы, цифры и дефис',
  'builderForm.headline': 'Профессиональный заголовок',
  'builderForm.bio': 'Обо мне',
  'builderForm.location': 'Местоположение',
  'builderForm.avatarUrl': 'URL аватара (необязательно)',
  'builderForm.skillName': 'Название навыка',
  'builderForm.role': 'Должность',
  'builderForm.organization': 'Организация',
  'builderForm.period': 'Период',
  'builderForm.description': 'Описание',
  'builderForm.institution': 'Учебное заведение',
  'builderForm.qualification': 'Специальность или квалификация',
  'builderForm.linkLabel': 'Название ссылки',
  'builderForm.linkUrl': 'URL',
  'builderForm.linkKind': 'Тип ссылки',
  'builderForm.kindOther': 'Другая',
  'builderForm.kindGitHub': 'GitHub',
  'builderForm.kindWebsite': 'Сайт',
  'builderForm.kindLinkedIn': 'LinkedIn',
  'builderForm.resumeText': 'Резюме',
  'builderForm.resumeHint': 'Обычный текст с переносами строк. Он появится в блоке Resume вашего портфолио.',
  'builderForm.projectName': 'Название проекта',
  'builderForm.technologies': 'Технологии',
  'builderForm.technologiesHint': 'Через запятую, например Flutter, Dart',
  'builderForm.repositoryUrl': 'URL репозитория (необязательно)',
  'builderForm.liveUrl': 'URL демо (необязательно)',
  'builderForm.featured': 'Featured: показывать среди избранных',
  'builderForm.visible': 'Показывать проект в портфолио',
  'builderForm.required': 'Заполните поле.',
  'builderForm.tooLong': 'Не более {limit} символов.',
  'builderForm.invalidUsername': 'Используйте 3–30 строчных латинских букв, цифр или дефисов. Первый и последний символ — буква или цифра.',
  'builderForm.invalidUrl':
      'Введите полный http/https URL без пробелов и данных входа.',
  'builderForm.invalidContent': 'Проверьте данные черновика.',
  'builderForm.tooManyTechnologies': 'Не более {limit} технологий.',
  'builderForm.technologyTooLong':
      'Название технологии — не более {limit} символов.',
  'builderForm.loading': 'Открываем черновик',
  'builderForm.loadingHint': 'Читаем данные, сохранённые на этом устройстве.',
  'builderForm.unavailable': 'Редактор недоступен',
  'builderForm.corrupted': 'Сохранённый черновик повреждён. Исходная запись сохранена; перезапись заблокирована.',
  'builderForm.unsupportedVersion': 'Черновик записан в другой версии формата. Исходная запись сохранена; перезапись заблокирована.',
  'builderForm.unavailableHint':
      'Не удалось безопасно открыть черновик. Сохранённые данные не изменены.',
  'builderForm.noContent': 'Builder ещё не начат',
  'builderForm.noContentHint': 'Откройте Builder и создайте свой черновик.',
  'builderForm.openBuilder': 'Открыть Builder',
  'builderForm.empty': 'Список пока пуст',
  'builderForm.emptyHint':
      'Добавьте запись. Изменения появятся в черновике после «Применить».',
  'builderForm.projectMissing': 'Проект не найден',
  'builderForm.projectMissingHint':
      'Этот проект больше не находится в черновике. Вернитесь в Builder.',
};

const builderFormEnglishStrings = <String, String>{
  'builderForm.profileTitle': 'Edit profile',
  'builderForm.skillsTitle': 'Skills',
  'builderForm.experienceTitle': 'Experience',
  'builderForm.educationTitle': 'Education',
  'builderForm.linksTitle': 'Links',
  'builderForm.resumeTitle': 'Resume text',
  'builderForm.newProjectTitle': 'New manual project',
  'builderForm.editProjectTitle': 'Edit project',
  'builderForm.applyHint': 'Apply your changes to the draft, then save it on your device in Builder.',
  'builderForm.apply': 'Apply',
  'builderForm.cancel': 'Cancel',
  'builderForm.add': 'Add',
  'builderForm.addOrUpdate': 'Done',
  'builderForm.edit': 'Edit',
  'builderForm.delete': 'Delete',
  'builderForm.name': 'Name',
  'builderForm.username': 'Username',
  'builderForm.usernameHint':
      '3–30 characters: lowercase letters, digits and hyphens',
  'builderForm.headline': 'Professional headline',
  'builderForm.bio': 'About me',
  'builderForm.location': 'Location',
  'builderForm.avatarUrl': 'Avatar URL (optional)',
  'builderForm.skillName': 'Skill name',
  'builderForm.role': 'Role',
  'builderForm.organization': 'Organization',
  'builderForm.period': 'Period',
  'builderForm.description': 'Description',
  'builderForm.institution': 'Institution',
  'builderForm.qualification': 'Qualification',
  'builderForm.linkLabel': 'Link label',
  'builderForm.linkUrl': 'URL',
  'builderForm.linkKind': 'Link type',
  'builderForm.kindOther': 'Other',
  'builderForm.kindGitHub': 'GitHub',
  'builderForm.kindWebsite': 'Website',
  'builderForm.kindLinkedIn': 'LinkedIn',
  'builderForm.resumeText': 'Resume',
  'builderForm.resumeHint': 'Plain text with line breaks. It will appear in the Resume block of your portfolio.',
  'builderForm.projectName': 'Project title',
  'builderForm.technologies': 'Technologies',
  'builderForm.technologiesHint':
      'Separate with commas, for example Flutter, Dart',
  'builderForm.repositoryUrl': 'Repository URL (optional)',
  'builderForm.liveUrl': 'Demo URL (optional)',
  'builderForm.featured': 'Featured: show among selected projects',
  'builderForm.visible': 'Show project in portfolio',
  'builderForm.required': 'Complete this field.',
  'builderForm.tooLong': 'Use no more than {limit} characters.',
  'builderForm.invalidUsername': 'Use 3–30 lowercase letters, digits or hyphens. Start and end with a letter or digit.',
  'builderForm.invalidUrl':
      'Enter a full http/https URL without spaces or sign-in information.',
  'builderForm.invalidContent': 'Check the draft content.',
  'builderForm.tooManyTechnologies': 'Use no more than {limit} technologies.',
  'builderForm.technologyTooLong':
      'A technology name can contain up to {limit} characters.',
  'builderForm.loading': 'Opening draft',
  'builderForm.loadingHint': 'Reading data saved on this device.',
  'builderForm.unavailable': 'Editor unavailable',
  'builderForm.corrupted': 'The saved draft is corrupted. The original record is preserved and cannot be overwritten.',
  'builderForm.unsupportedVersion': 'The draft uses a different format version. The original record is preserved and cannot be overwritten.',
  'builderForm.unavailableHint':
      'The draft could not be opened safely. Saved data has not changed.',
  'builderForm.noContent': 'Builder has not started',
  'builderForm.noContentHint': 'Open Builder and create your draft.',
  'builderForm.openBuilder': 'Open Builder',
  'builderForm.empty': 'This list is empty',
  'builderForm.emptyHint':
      'Add an entry. Your changes will reach the draft when you press Apply.',
  'builderForm.projectMissing': 'Project not found',
  'builderForm.projectMissingHint':
      'This project is no longer in the draft. Return to Builder.',
};
