const builderRussianStrings = <String, String>{
  'builder.title': 'Редактор портфолио',
  'builder.subtitle': 'Собери своё портфолио и проверь предпросмотр. Сохранение действует только на этом устройстве.',
  'builder.start': 'Начать портфолио',
  'builder.emptyTitle': 'Портфолио ещё не создано',
  'builder.emptyMessage':
      'Начни с пустого черновика. Личные заметки сохранятся отдельно.',
  'builder.save': 'Сохранить портфолио',
  'builder.saving': 'Сохраняем портфолио…',
  'builder.saved': 'Сохранено на устройстве',
  'builder.unsaved': 'Есть несохранённые изменения',
  'builder.pending': 'Ожидает синхронизации. Облако пока не подключено.',
  'builder.revision': 'Последняя сохранённая версия: {revision}',
  'builder.preview': 'Предпросмотр',
  'builder.previewTitle': 'Предпросмотр портфолио',
  'builder.previewPrivate':
      'Локальный предпросмотр. Портфолио не опубликовано.',
  'builder.previewEmpty': 'В видимых блоках пока нет данных',
  'builder.previewEmptyHint':
      'Добавь содержимое в редакторе или включи заполненные блоки.',
  'builder.back': 'Назад к портфолио',
  'builder.backEditor': 'Назад к редактору',
  'builder.sections': 'Содержимое',
  'builder.section.profile': 'Профиль и обо мне',
  'builder.section.skills': 'Навыки',
  'builder.section.experience': 'Опыт работы',
  'builder.section.education': 'Образование',
  'builder.section.links': 'Ссылки',
  'builder.section.resume': 'Резюме',
  'builder.count': 'Элементов: {count}',
  'builder.notes': 'Личные заметки',
  'builder.notesPrivate':
      'Заметки не входят в портфолио и не показываются в предпросмотре.',
  'builder.projects': 'Ручные проекты',
  'builder.addProject': 'Добавить проект',
  'builder.noProjects': 'Добавь первый проект',
  'builder.editProject': 'Изменить проект',
  'builder.deleteProject': 'Удалить {title}',
  'builder.deleteTitle': 'Удалить проект?',
  'builder.deleteMessage': 'Проект будет удалён из текущего черновика. Сохрани портфолио, чтобы записать изменение на устройстве.',
  'builder.delete': 'Удалить',
  'builder.cancel': 'Отмена',
  'builder.featured': 'Featured',
  'builder.visibleProject': 'Показывать проект',
  'builder.blocks': 'Порядок и видимость блоков',
  'builder.block.profile': 'Профиль',
  'builder.block.about': 'Обо мне',
  'builder.block.skills': 'Навыки',
  'builder.block.featuredProjects': 'Featured проекты',
  'builder.block.experience': 'Опыт работы',
  'builder.block.education': 'Образование',
  'builder.block.github': 'GitHub',
  'builder.block.links': 'Ссылки',
  'builder.block.resume': 'Резюме',
  'builder.block.location': 'Местоположение',
  'builder.block.visible': 'Показывать {block}',
  'builder.block.up': 'Выше: {block}',
  'builder.block.down': 'Ниже: {block}',
  'builder.theme': 'Тема портфолио',
  'builder.theme.dark': 'Тёмная',
  'builder.theme.light': 'Светлая',
  'builder.completion': 'Готовность: {percent}%',
  'builder.completionCount':
      'Заполнено {completed} из {total} основных разделов',
  'builder.completionMissing': 'Осталось: {steps}',
  'builder.step.profile': 'профиль',
  'builder.step.about': 'обо мне',
  'builder.step.skills': 'навыки',
  'builder.step.projects': 'проекты',
  'builder.step.links': 'ссылки',
  'builder.invalid': 'Исправь некорректные поля перед сохранением. Введённые данные остались в черновике.',
  'builder.failure.title': 'Изменения не сохранены',
  'builder.failure.conflict': 'Сохранённая версия изменилась. Твои правки остались в редакторе. Открой сохранённую версию, чтобы продолжить.',
  'builder.failure.invalidContent':
      'В портфолио есть некорректные поля. Исправь их перед сохранением.',
  'builder.reload': 'Открыть сохранённую версию',
  'builder.reloadTitle': 'Открыть сохранённую версию?',
  'builder.reloadMessage': 'Текущие несохранённые правки портфолио и личных заметок будут отброшены.',
  'builder.reloadConfirm': 'Открыть сохранённое',
};

const builderEnglishStrings = <String, String>{
  'builder.title': 'Portfolio editor',
  'builder.subtitle': 'Build your portfolio and check the preview. Saving applies only to this device.',
  'builder.start': 'Start portfolio',
  'builder.emptyTitle': 'No portfolio yet',
  'builder.emptyMessage':
      'Start with an empty draft. Your private notes remain separate.',
  'builder.save': 'Save portfolio',
  'builder.saving': 'Saving portfolio…',
  'builder.saved': 'Saved on device',
  'builder.unsaved': 'You have unsaved changes',
  'builder.pending':
      'Pending synchronization. Cloud sync is not connected yet.',
  'builder.revision': 'Last saved revision: {revision}',
  'builder.preview': 'Preview',
  'builder.previewTitle': 'Portfolio preview',
  'builder.previewPrivate': 'Local preview. This portfolio is not published.',
  'builder.previewEmpty': 'Visible blocks have no content yet',
  'builder.previewEmptyHint':
      'Add content in the editor or show populated blocks.',
  'builder.back': 'Back to portfolio',
  'builder.backEditor': 'Back to editor',
  'builder.sections': 'Content',
  'builder.section.profile': 'Profile and about',
  'builder.section.skills': 'Skills',
  'builder.section.experience': 'Experience',
  'builder.section.education': 'Education',
  'builder.section.links': 'Links',
  'builder.section.resume': 'Resume',
  'builder.count': 'Items: {count}',
  'builder.notes': 'Private notes',
  'builder.notesPrivate':
      'Notes are not part of the portfolio and do not appear in the preview.',
  'builder.projects': 'Manual projects',
  'builder.addProject': 'Add project',
  'builder.noProjects': 'Add your first project',
  'builder.editProject': 'Edit project',
  'builder.deleteProject': 'Delete {title}',
  'builder.deleteTitle': 'Delete project?',
  'builder.deleteMessage': 'The project will be removed from the working draft. Save the portfolio to store this change on device.',
  'builder.delete': 'Delete',
  'builder.cancel': 'Cancel',
  'builder.featured': 'Featured',
  'builder.visibleProject': 'Show project',
  'builder.blocks': 'Block order and visibility',
  'builder.block.profile': 'Profile',
  'builder.block.about': 'About',
  'builder.block.skills': 'Skills',
  'builder.block.featuredProjects': 'Featured projects',
  'builder.block.experience': 'Experience',
  'builder.block.education': 'Education',
  'builder.block.github': 'GitHub',
  'builder.block.links': 'Links',
  'builder.block.resume': 'Resume',
  'builder.block.location': 'Location',
  'builder.block.visible': 'Show {block}',
  'builder.block.up': 'Move up: {block}',
  'builder.block.down': 'Move down: {block}',
  'builder.theme': 'Portfolio theme',
  'builder.theme.dark': 'Dark',
  'builder.theme.light': 'Light',
  'builder.completion': 'Completion: {percent}%',
  'builder.completionCount': '{completed} of {total} core sections completed',
  'builder.completionMissing': 'Remaining: {steps}',
  'builder.step.profile': 'profile',
  'builder.step.about': 'about',
  'builder.step.skills': 'skills',
  'builder.step.projects': 'projects',
  'builder.step.links': 'links',
  'builder.invalid': 'Correct invalid fields before saving. Your entered data remains in the draft.',
  'builder.failure.title': 'Changes were not saved',
  'builder.failure.conflict': 'The saved revision changed. Your edits remain in the editor. Open the saved revision to continue.',
  'builder.failure.invalidContent':
      'The portfolio contains invalid fields. Correct them before saving.',
  'builder.reload': 'Open saved revision',
  'builder.reloadTitle': 'Open saved revision?',
  'builder.reloadMessage':
      'Current unsaved portfolio edits and private notes will be discarded.',
  'builder.reloadConfirm': 'Open saved data',
};
