const russianDocumentEditorStrings = <String, String>{
  'documentEditor.createResume': 'Создать резюме',
  'documentEditor.createPortfolio': 'Создать портфолио',
  'documentEditor.editResume': 'Редактор резюме',
  'documentEditor.editPortfolio': 'Редактор портфолио',
  'documentEditor.step': 'Шаг {step} из 5 · {label}',
  'documentEditor.profile': 'Профиль',
  'documentEditor.contacts': 'Контакты',
  'documentEditor.qualifications': 'Опыт и образование',
  'documentEditor.projects': 'Навыки и проекты',
  'documentEditor.appearance': 'Порядок и оформление',
  'documentEditor.preview': 'Предпросмотр',
  'documentEditor.title': 'Название документа',
  'documentEditor.titleHint': 'Название видно только вам',
  'documentEditor.name': 'Полное имя',
  'documentEditor.role': 'Роль',
  'documentEditor.bio': 'Краткое описание',
  'documentEditor.location': 'Местоположение',
  'documentEditor.profileHint': 'Изменения относятся только к этому документу. Фото и описание необязательны.',
  'documentEditor.showPhoto': 'Показывать фото',
  'documentEditor.noPhoto': 'Фото не добавлено',
  'documentEditor.photo': 'Фото документа',
  'documentEditor.photoHint': 'Фото войдёт в этот документ после сохранения.',
  'documentEditor.useProfilePhoto': 'Взять фото профиля',
  'documentEditor.removePhoto': 'Убрать фото из документа',
  'documentEditor.contactsHint': 'Выберите публичные ссылки из общей базы или добавьте ссылку только для этого документа.',
  'documentEditor.addLink': 'Добавить свою ссылку',
  'documentEditor.linkLabel': 'Подпись ссылки',
  'documentEditor.linkUrl': 'URL',
  'documentEditor.experience': 'Опыт работы',
  'documentEditor.education': 'Образование',
  'documentEditor.skills': 'Технологии',
  'documentEditor.libraryProjects': 'Проекты из библиотеки',
  'documentEditor.addExperience': 'Добавить опыт',
  'documentEditor.addEducation': 'Добавить образование',
  'documentEditor.addSkill': 'Добавить технологию',
  'documentEditor.addProject': 'Создать проект',
  'documentEditor.editNewProject': 'Редактировать новый проект',
  'documentEditor.organization': 'Организация',
  'documentEditor.period': 'Период',
  'documentEditor.description': 'Описание',
  'documentEditor.institution': 'Учебное заведение',
  'documentEditor.qualification': 'Специальность',
  'documentEditor.skillName': 'Название технологии',
  'documentEditor.empty': 'Пока нет записей',
  'documentEditor.libraryEmpty': 'Выберите сохранённый проект или создайте новый здесь. Новый проект войдёт в библиотеку после сохранения документа.',
  'documentEditor.visible': 'Показывать',
  'documentEditor.featured': 'Основной проект',
  'documentEditor.moveUp': 'Выше',
  'documentEditor.moveDown': 'Ниже',
  'documentEditor.detach': 'Убрать из документа',
  'documentEditor.attachResume': 'Прикреплённое резюме',
  'documentEditor.noResume': 'Не выбрано',
  'documentEditor.resumePrivate': 'Резюме прикреплено к черновику. Публичная ссылка появится после отдельной публикации.',
  'documentEditor.dark': 'Тёмное оформление',
  'documentEditor.light': 'Светлое оформление',
  'documentEditor.unsaved': 'Черновик · изменения не сохранены',
  'documentEditor.saved': 'Черновик сохранён на устройстве',
  'documentEditor.save': 'Сохранить',
  'documentEditor.saving': 'Сохраняем на устройстве…',
  'documentEditor.saveError': 'Не удалось сохранить. Введённые данные остались в редакторе; попробуйте снова.',
  'documentEditor.next': 'Далее',
  'documentEditor.skip': 'Пропустить',
  'documentEditor.back': 'Назад',
  'documentEditor.cancel': 'Отмена',
  'documentEditor.publish': 'К публикации',
  'documentEditor.publishUnavailable': 'Публикация нескольких документов пока не подключена. Сохранение остаётся приватным и не создаёт публичную ссылку.',
  'documentEditor.leaveTitle': 'Сохранить изменения?',
  'documentEditor.leaveHint': 'Вы можете сохранить этот документ, выйти без сохранения или продолжить редактирование.',
  'documentEditor.discard': 'Не сохранять',
  'documentEditor.stay': 'Продолжить',
  'documentEditor.ownerChanged':
      'Аккаунт изменился. Откройте документ заново из библиотеки.',
  'documentEditor.conflict': 'Этот документ изменился или был удалён в другой сессии. Сохранение остановлено, чтобы не затереть новую версию.',
  'documentEditor.reload': 'Загрузить новую версию',
  'documentEditor.reloadTitle': 'Заменить введённые данные?',
  'documentEditor.reloadHint': 'Только буфер этого редактора будет заменён последней сохранённой версией. Изменения общей базы и заметок сохранятся.',
  'documentEditor.missing': 'Документ больше недоступен',
  'documentEditor.previewEmpty': 'Добавьте имя и роль в разделе «Профиль».',
};

const englishDocumentEditorStrings = <String, String>{
  'documentEditor.createResume': 'Create resume',
  'documentEditor.createPortfolio': 'Create portfolio',
  'documentEditor.editResume': 'Resume editor',
  'documentEditor.editPortfolio': 'Portfolio editor',
  'documentEditor.step': 'Step {step} of 5 · {label}',
  'documentEditor.profile': 'Profile',
  'documentEditor.contacts': 'Contacts',
  'documentEditor.qualifications': 'Experience and education',
  'documentEditor.projects': 'Skills and projects',
  'documentEditor.appearance': 'Order and appearance',
  'documentEditor.preview': 'Preview',
  'documentEditor.title': 'Document title',
  'documentEditor.titleHint': 'Only you can see this title',
  'documentEditor.name': 'Full name',
  'documentEditor.role': 'Role',
  'documentEditor.bio': 'Short description',
  'documentEditor.location': 'Location',
  'documentEditor.profileHint': 'These changes apply only to this document. Photo and description are optional.',
  'documentEditor.showPhoto': 'Show photo',
  'documentEditor.noPhoto': 'No photo added',
  'documentEditor.photo': 'Document photo',
  'documentEditor.photoHint':
      'The photo will be included in this document after saving.',
  'documentEditor.useProfilePhoto': 'Use profile photo',
  'documentEditor.removePhoto': 'Remove document photo',
  'documentEditor.contactsHint': 'Choose public links from your shared profile or add a link only to this document.',
  'documentEditor.addLink': 'Add a custom link',
  'documentEditor.linkLabel': 'Link label',
  'documentEditor.linkUrl': 'URL',
  'documentEditor.experience': 'Work experience',
  'documentEditor.education': 'Education',
  'documentEditor.skills': 'Technologies',
  'documentEditor.libraryProjects': 'Projects from library',
  'documentEditor.addExperience': 'Add experience',
  'documentEditor.addEducation': 'Add education',
  'documentEditor.addSkill': 'Add technology',
  'documentEditor.addProject': 'Create project',
  'documentEditor.editNewProject': 'Edit new project',
  'documentEditor.organization': 'Organization',
  'documentEditor.period': 'Period',
  'documentEditor.description': 'Description',
  'documentEditor.institution': 'Institution',
  'documentEditor.qualification': 'Qualification',
  'documentEditor.skillName': 'Technology name',
  'documentEditor.empty': 'No records yet',
  'documentEditor.libraryEmpty': 'Choose a saved project or create one here. New projects join the library when you save the document.',
  'documentEditor.visible': 'Show',
  'documentEditor.featured': 'Featured project',
  'documentEditor.moveUp': 'Move up',
  'documentEditor.moveDown': 'Move down',
  'documentEditor.detach': 'Remove from document',
  'documentEditor.attachResume': 'Attached resume',
  'documentEditor.noResume': 'Not selected',
  'documentEditor.resumePrivate': 'This resume is attached to the draft. Its public link requires a separate publication.',
  'documentEditor.dark': 'Dark appearance',
  'documentEditor.light': 'Light appearance',
  'documentEditor.unsaved': 'Draft · unsaved changes',
  'documentEditor.saved': 'Draft saved on device',
  'documentEditor.save': 'Save',
  'documentEditor.saving': 'Saving on device…',
  'documentEditor.saveError':
      'Could not save. Your input remains in the editor; try again.',
  'documentEditor.next': 'Next',
  'documentEditor.skip': 'Skip',
  'documentEditor.back': 'Back',
  'documentEditor.cancel': 'Cancel',
  'documentEditor.publish': 'Publish',
  'documentEditor.publishUnavailable': 'Multiple document publication is not connected yet. Saving stays private and does not create a public link.',
  'documentEditor.leaveTitle': 'Save changes?',
  'documentEditor.leaveHint':
      'Save this document, leave without saving, or continue editing.',
  'documentEditor.discard': 'Discard',
  'documentEditor.stay': 'Continue editing',
  'documentEditor.ownerChanged':
      'Your account changed. Open the document again from the library.',
  'documentEditor.conflict': 'This document changed or was deleted in another session. Saving is stopped to protect the newer version.',
  'documentEditor.reload': 'Load latest version',
  'documentEditor.reloadTitle': 'Replace your input?',
  'documentEditor.reloadHint': 'Only this editor buffer will be replaced with the latest saved version. Shared profile and note changes will remain.',
  'documentEditor.missing': 'Document is no longer available',
  'documentEditor.previewEmpty': 'Add your name and role in Profile.',
};
