const russianDraftStrings = <String, String>{
  'draft.open': 'Локальные заметки',
  'draft.title': 'Локальный черновик',
  'draft.back': 'Назад к портфолио',
  'draft.intro': 'Заметки к портфолио',
  'draft.scope': 'Запиши идеи, описание себя или планы проектов. Заметки сохраняются на этом устройстве и доступны без сети.',
  'draft.notes': 'Заметки',
  'draft.hint': 'Что стоит добавить в портфолио?',
  'draft.save': 'Сохранить на устройстве',
  'draft.saving': 'Сохраняем заметки…',
  'draft.loading': 'Открываем черновик',
  'draft.loadingMessage': 'Читаем заметки, сохранённые на этом устройстве.',
  'draft.unsaved': 'Есть несохранённые изменения',
  'draft.empty': 'Заметки ещё не сохранены',
  'draft.saved': 'Заметки сохранены на устройстве',
  'draft.pending':
      'Ожидает синхронизации. Облачная синхронизация пока не подключена.',
  'draft.revision': 'Последняя сохранённая версия: {revision}',
  'draft.updatedAt': 'Сохранено: {time}',
  'draft.readFailure': 'Не удалось открыть черновик',
  'draft.saveFailure': 'Заметки не сохранены',
  'draft.unavailable':
      'Локальное хранилище недоступно. Повтори действие позже.',
  'draft.corrupted': 'Сохранённый черновик повреждён. Исходная запись сохранена; перезапись заблокирована.',
  'draft.unsupportedVersion': 'Черновик записан в другой версии формата. Исходная запись сохранена; перезапись заблокирована.',
  'draft.inputRetained':
      'Твои введённые заметки остались в поле. Они ещё не сохранены.',
  'draft.retryRead': 'Повторить чтение',
};

const englishDraftStrings = <String, String>{
  'draft.open': 'Local notes',
  'draft.title': 'Local draft',
  'draft.back': 'Back to portfolio',
  'draft.intro': 'Portfolio notes',
  'draft.scope': 'Write ideas, your introduction or project plans. Notes are saved on this device and available offline.',
  'draft.notes': 'Notes',
  'draft.hint': 'What would you like to add to your portfolio?',
  'draft.save': 'Save on device',
  'draft.saving': 'Saving notes…',
  'draft.loading': 'Opening draft',
  'draft.loadingMessage': 'Reading notes saved on this device.',
  'draft.unsaved': 'You have unsaved changes',
  'draft.empty': 'Notes have not been saved yet',
  'draft.saved': 'Notes saved on this device',
  'draft.pending': 'Pending synchronization. Cloud sync is not connected yet.',
  'draft.revision': 'Last saved revision: {revision}',
  'draft.updatedAt': 'Saved: {time}',
  'draft.readFailure': 'Could not open draft',
  'draft.saveFailure': 'Notes were not saved',
  'draft.unavailable': 'Local storage is unavailable. Try again later.',
  'draft.corrupted': 'The saved draft is corrupted. The original record is preserved and cannot be overwritten.',
  'draft.unsupportedVersion': 'The draft uses a different format version. The original record is preserved and cannot be overwritten.',
  'draft.inputRetained':
      'Your entered notes remain in the field. They have not been saved yet.',
  'draft.retryRead': 'Retry reading',
};
