const russianGitHubStrings = <String, String>{
  'github.back': 'Назад к проектам',
  'github.title': 'Найди свои репозитории',
  'github.hint': 'Просмотр публичного GitHub без входа. Данные остаются источником: портфолио и демонстрационный профиль не меняются.',
  'github.username': 'Username GitHub',
  'github.usernameHint': 'Например, octocat',
  'github.usernameEmpty': 'Введи username GitHub',
  'github.usernameInvalid': 'Используй до 39 букв, цифр и одиночных дефисов',
  'github.load': 'Загрузить профиль',
  'github.loading': 'Загрузка GitHub',
  'github.loadingHint':
      'Получаем публичный профиль и первую страницу репозиториев.',
  'github.refresh': 'Обновить GitHub',
  'github.search': 'Поиск репозиториев',
  'github.searchHint': 'Название, описание или язык',
  'github.filter.all': 'Все',
  'github.filter.originals': 'Оригинальные',
  'github.filter.forks': 'Forks',
  'github.filter.archived': 'Архив',
  'github.counts': 'Показано: {visible} · Загружено: {loaded}',
  'github.searchScope': 'Поиск и фильтры применяются к загруженным страницам.',
  'github.emptyUsername': 'Введи username',
  'github.emptyUsernameHint':
      'Покажем профиль и доступные публичные репозитории.',
  'github.emptyRepos': 'Публичных репозиториев нет',
  'github.emptySearch': 'Ничего не найдено',
  'github.emptyReposHint': 'Можно попробовать другой username.',
  'github.emptySearchHint':
      'Измени поиск, сбрось фильтры или загрузи следующую страницу.',
  'github.reset': 'Сбросить поиск и фильтры',
  'github.more': 'Загрузить ещё',
  'github.publicRepos': 'Публичных репозиториев: {count}',
  'github.noDescription': 'Описание не добавлено',
  'github.noLanguage': 'Язык не указан',
  'github.copyLink': 'Скопировать ссылку',
  'github.linkCopied': 'Ссылка скопирована',
  'github.cache.title': 'Сохранённая копия GitHub',
  'github.cache.hint': 'Не удалось обновить GitHub. Показаны ранее загруженные данные; повторите обновление при восстановлении соединения.',
  'github.cache.date': 'Последняя проверка: {date}',
  'github.cache.storageTitle': 'Копия на устройстве недоступна',
  'github.cache.storageHint': 'Данные загружены, но локальное хранение недоступно. Доступ без сети для этого ответа не гарантирован.',
  'github.failure.invalidUsername.title': 'Проверь username',
  'github.failure.invalidUsername.message':
      'Введи имя аккаунта GitHub без ссылки.',
  'github.failure.notFound.title': 'Профиль не найден',
  'github.failure.notFound.message':
      'Проверь username. Доступны только публичные данные GitHub.',
  'github.failure.network.title': 'Нет соединения',
  'github.failure.network.message':
      'Проверь доступ к интернету и повтори запрос.',
  'github.failure.timeout.title': 'GitHub не ответил вовремя',
  'github.failure.timeout.message':
      'Соединение заняло слишком много времени. Попробуй ещё раз.',
  'github.failure.rateLimited.title': 'Лимит запросов GitHub',
  'github.failure.rateLimited.message':
      'GitHub временно ограничил запросы. Подожди перед повтором.',
  'github.failure.forbidden.title': 'Данные недоступны',
  'github.failure.forbidden.message':
      'GitHub запретил этот запрос. Попробуй другой публичный профиль.',
  'github.failure.server.title': 'GitHub временно недоступен',
  'github.failure.server.message': 'Повтори запрос немного позже.',
  'github.failure.invalidResponse.title': 'Не удалось прочитать данные',
  'github.failure.invalidResponse.message':
      'GitHub вернул неожиданный ответ. Повтори запрос.',
  'github.failure.cancelled.title': 'Запрос отменён',
  'github.failure.cancelled.message': 'Можно загрузить профиль снова.',
  'github.retryAfter': ' Можно повторить после {time}.',
};

const englishGitHubStrings = <String, String>{
  'github.back': 'Back to projects',
  'github.title': 'Find your repositories',
  'github.hint': 'Browse public GitHub data without signing in. This source does not change your portfolio or demo profile.',
  'github.username': 'GitHub username',
  'github.usernameHint': 'For example, octocat',
  'github.usernameEmpty': 'Enter a GitHub username',
  'github.usernameInvalid': 'Use up to 39 letters, digits and single hyphens',
  'github.load': 'Load profile',
  'github.loading': 'Loading GitHub',
  'github.loadingHint':
      'Fetching the public profile and first repository page.',
  'github.refresh': 'Refresh GitHub',
  'github.search': 'Search repositories',
  'github.searchHint': 'Name, description or language',
  'github.filter.all': 'All',
  'github.filter.originals': 'Originals',
  'github.filter.forks': 'Forks',
  'github.filter.archived': 'Archived',
  'github.counts': 'Shown: {visible} · Loaded: {loaded}',
  'github.searchScope': 'Search and filters apply to loaded pages.',
  'github.emptyUsername': 'Enter a username',
  'github.emptyUsernameHint':
      'View the profile and available public repositories.',
  'github.emptyRepos': 'No public repositories',
  'github.emptySearch': 'No matches',
  'github.emptyReposHint': 'Try another username.',
  'github.emptySearchHint':
      'Change your search, reset filters or load the next page.',
  'github.reset': 'Reset search and filters',
  'github.more': 'Load more',
  'github.publicRepos': 'Public repositories: {count}',
  'github.noDescription': 'No description',
  'github.noLanguage': 'Language not specified',
  'github.copyLink': 'Copy link',
  'github.linkCopied': 'Link copied',
  'github.cache.title': 'Saved GitHub copy',
  'github.cache.hint': 'GitHub could not be refreshed. Previously loaded data is shown; refresh again when the connection returns.',
  'github.cache.date': 'Last checked: {date}',
  'github.cache.storageTitle': 'Device copy unavailable',
  'github.cache.storageHint': 'Data was loaded, but local storage is unavailable. Offline access to this response is not guaranteed.',
  'github.failure.invalidUsername.title': 'Check the username',
  'github.failure.invalidUsername.message':
      'Enter a GitHub account name, without a URL.',
  'github.failure.notFound.title': 'Profile not found',
  'github.failure.notFound.message':
      'Check the username. Only public GitHub data is available.',
  'github.failure.network.title': 'No connection',
  'github.failure.network.message':
      'Check your internet connection and try again.',
  'github.failure.timeout.title': 'GitHub timed out',
  'github.failure.timeout.message': 'The connection took too long. Try again.',
  'github.failure.rateLimited.title': 'GitHub request limit',
  'github.failure.rateLimited.message':
      'GitHub temporarily limited requests. Wait before retrying.',
  'github.failure.forbidden.title': 'Data unavailable',
  'github.failure.forbidden.message':
      'GitHub rejected this request. Try another public profile.',
  'github.failure.server.title': 'GitHub temporarily unavailable',
  'github.failure.server.message': 'Try again a little later.',
  'github.failure.invalidResponse.title': 'Could not read data',
  'github.failure.invalidResponse.message':
      'GitHub returned an unexpected response. Try again.',
  'github.failure.cancelled.title': 'Request cancelled',
  'github.failure.cancelled.message': 'You can load the profile again.',
  'github.retryAfter': ' You can retry after {time}.',
};
