const russianGitHubSyncStrings = <String, String>{
  'githubSync.status.newRepository': 'Новый для портфолио',
  'githubSync.status.synced': 'В портфолио · без изменений источника',
  'githubSync.status.changesAvailable': 'Есть изменения GitHub',
  'githubSync.status.ignored': 'Пропущен',
  'githubSync.preview': 'Предпросмотр',
  'githubSync.add': 'Добавить в портфолио',
  'githubSync.ignore': 'Пропустить эту версию',
  'githubSync.review': 'Посмотреть изменения',
  'githubSync.accept': 'Принять изменения',
  'githubSync.edit': 'Редактировать',
  'githubSync.close': 'Закрыть',
  'githubSync.cancel': 'Отмена',
  'githubSync.signIn': 'Войти для импорта',
  'githubSync.actionFailed': 'Черновик или источник изменился, либо действие сейчас недоступно. Проверь данные и повтори попытку.',
  'githubSync.applied': 'Черновик изменён. Сохрани изменения.',
  'githubSync.invalidSource': 'Данные репозитория не подходят для импорта. Обнови GitHub и проверь источник.',
  'githubSync.invalidDraft':
      'Данные черновика требуют проверки. Открой редактор портфолио.',
  'githubSync.editorStale': 'Проект или аккаунт изменился, пока форма была открыта. Введённый текст сохранён в форме. Открой проект заново, чтобы применить правки к актуальной версии.',
  'githubSync.previewNote': 'Публичный источник GitHub. Портфолио не меняется.',
  'githubSync.reviewNote': 'Обновим черновик, сохранив твои правки. Сохранение и публикация — отдельно.',
  'githubSync.previous': 'Принятый источник',
  'githubSync.incoming': 'Сейчас в GitHub',
  'githubSync.override': 'Твоё значение сохранится',
  'githubSync.metadataChanged':
      'Обновилась активность GitHub. Твои поля сохранятся.',
  'githubSync.metadata.fullName': 'Полное имя репозитория',
  'githubSync.metadata.stars': 'Звёзды',
  'githubSync.metadata.forks': 'Количество forks',
  'githubSync.metadata.isFork': 'Репозиторий является fork',
  'githubSync.metadata.archived': 'Архивный репозиторий',
  'githubSync.metadata.updatedAt': 'Обновлён в GitHub (UTC)',
  'githubSync.yes': 'Да',
  'githubSync.no': 'Нет',
  'githubSync.field.title': 'Название',
  'githubSync.field.description': 'Описание',
  'githubSync.field.technologies': 'Технологии',
  'githubSync.field.repositoryUrl': 'Ссылка на repository',
  'githubSync.empty': 'Не указано',
  'githubSync.draftNote':
      'Изменения в черновике. Сохранение и публикация — отдельные действия.',
  'githubSync.unsaved': 'Есть несохранённые изменения черновика',
  'githubSync.saving': 'Сохраняем черновик…',
  'githubSync.saved': 'Черновик сохранён на устройстве',
  'githubSync.emptyDraft': 'Черновик ещё не сохранён',
  'githubSync.pending': 'Черновик сохранён · ожидает облачной синхронизации',
  'githubSync.save': 'Сохранить черновик',
  'githubSync.openBuilder': 'Редактор портфолио',
  'githubSync.projects': 'Проекты портфолио',
  'githubSync.projectsSubtitle': 'Проекты рабочего черновика: ручные и импортированные из GitHub. Скрытые записи доступны для редактирования.',
  'githubSync.githubCase': 'Проект из GitHub в вашем портфолио',
  'githubSync.sourceNote': 'Источник: {source} · рабочий черновик',
  'githubSync.editorNote': 'Проект связан с GitHub. Изменённые поля становятся твоими ручными правками и сохраняются при обновлении источника.',
};

const englishGitHubSyncStrings = <String, String>{
  'githubSync.status.newRepository': 'New to your portfolio',
  'githubSync.status.synced': 'In portfolio · source unchanged',
  'githubSync.status.changesAvailable': 'GitHub changes available',
  'githubSync.status.ignored': 'Ignored',
  'githubSync.preview': 'Preview',
  'githubSync.add': 'Add to portfolio',
  'githubSync.ignore': 'Ignore this version',
  'githubSync.review': 'Review changes',
  'githubSync.accept': 'Accept changes',
  'githubSync.edit': 'Edit',
  'githubSync.close': 'Close',
  'githubSync.cancel': 'Cancel',
  'githubSync.signIn': 'Sign in to import',
  'githubSync.actionFailed': 'The draft or source changed, or the action is unavailable. Check the data and try again.',
  'githubSync.applied': 'Draft updated. Save your changes.',
  'githubSync.invalidSource': 'Repository data cannot be imported. Refresh GitHub and check the source.',
  'githubSync.invalidDraft':
      'Draft data needs checking. Open the portfolio editor.',
  'githubSync.editorStale': 'The project or account changed while this form was open. Your input remains in the form. Reopen the project to edit the current version.',
  'githubSync.previewNote':
      'Public GitHub source. Your portfolio is unchanged.',
  'githubSync.reviewNote':
      'Updates the draft and keeps your edits. Save and publish separately.',
  'githubSync.previous': 'Accepted source',
  'githubSync.incoming': 'Current GitHub value',
  'githubSync.override': 'Your value will be preserved',
  'githubSync.metadataChanged':
      'GitHub activity changed. Your fields remain intact.',
  'githubSync.metadata.fullName': 'Full repository name',
  'githubSync.metadata.stars': 'Stars',
  'githubSync.metadata.forks': 'Fork count',
  'githubSync.metadata.isFork': 'Repository is a fork',
  'githubSync.metadata.archived': 'Archived repository',
  'githubSync.metadata.updatedAt': 'Updated on GitHub (UTC)',
  'githubSync.yes': 'Yes',
  'githubSync.no': 'No',
  'githubSync.field.title': 'Title',
  'githubSync.field.description': 'Description',
  'githubSync.field.technologies': 'Technologies',
  'githubSync.field.repositoryUrl': 'Repository URL',
  'githubSync.empty': 'Not provided',
  'githubSync.draftNote':
      'Changes are in your draft. Save and publish separately.',
  'githubSync.unsaved': 'Your draft has unsaved changes',
  'githubSync.saving': 'Saving draft…',
  'githubSync.saved': 'Draft saved on this device',
  'githubSync.emptyDraft': 'Draft has not been saved yet',
  'githubSync.pending': 'Draft saved · pending cloud synchronization',
  'githubSync.save': 'Save draft',
  'githubSync.openBuilder': 'Portfolio editor',
  'githubSync.projects': 'Portfolio projects',
  'githubSync.projectsSubtitle': 'Working draft projects: manual and imported from GitHub. Hidden entries remain available for editing.',
  'githubSync.githubCase': 'GitHub project in your portfolio',
  'githubSync.sourceNote': 'Source: {source} · working draft',
  'githubSync.editorNote': 'This project is linked to GitHub. Edited fields become your manual overrides and remain intact when the source updates.',
};
