const russianMobileParityStrings = <String, String>{
  'mobileParity.demoLink': 'Ссылка на демо',
  'mobileParity.noLink': 'Нет ссылки',
  'mobileParity.noLinkHint': 'Ссылка не добавлена',
  'mobileParity.copy': 'Копировать',
  'mobileParity.copied': 'Скопировано',
  'mobileParity.copyFailed': 'Не удалось скопировать ссылку.',
  'mobileParity.allTechnologies': 'Технологии проекта',
  'mobileParity.contribution': 'Мой вклад',
  'mobileParity.contributionHint': 'Что вы сделали в этом проекте',
  'mobileParity.cover': 'Обложка',
  'mobileParity.noCover': 'Без изображения',
  'mobileParity.coverHint':
      'В карточке будет нейтральный placeholder. Обложка необязательна.',
  'mobileParity.technologiesEmpty': 'Технологии не добавлены',
  'mobileParity.projectLibraryHint': 'Проект сохраняется в общей библиотеке. Включение в резюме и портфолио настраивается отдельно.',
  'mobileParity.preview': 'Предпросмотр карточки',
  'mobileParity.save': 'Сохранить',
  'mobileParity.unsaved': 'Есть несохранённые изменения',
  'mobileParity.saved': 'Нет несохранённых изменений',
  'mobileParity.projectSaveError':
      'Не удалось сохранить проект. Ввод сохранён в форме; повторите попытку.',
  'mobileParity.leaveTitle': 'Несохранённые изменения',
  'mobileParity.leaveHint': 'Изменения проекта ещё не сохранены.',
  'mobileParity.stay': 'Продолжить редактирование',
  'mobileParity.discard': 'Выйти без сохранения',
  'mobileParity.projectNameEmpty': 'Название проекта',
  'mobileParity.limit': 'До {limit} символов',
  'mobileParity.repositoryHint': 'Необязательно; https:// или http://',
  'mobileParity.demoHint': 'Необязательно; публичная демоссылка',
};

const englishMobileParityStrings = <String, String>{
  'mobileParity.demoLink': 'Demo link',
  'mobileParity.noLink': 'No link',
  'mobileParity.noLinkHint': 'No link added',
  'mobileParity.copy': 'Copy',
  'mobileParity.copied': 'Copied',
  'mobileParity.copyFailed': 'Unable to copy the link.',
  'mobileParity.allTechnologies': 'Project technologies',
  'mobileParity.contribution': 'My contribution',
  'mobileParity.contributionHint': 'What you contributed to this project',
  'mobileParity.cover': 'Cover',
  'mobileParity.noCover': 'No image',
  'mobileParity.coverHint':
      'The card will use a neutral placeholder. A cover is optional.',
  'mobileParity.technologiesEmpty': 'No technologies added',
  'mobileParity.projectLibraryHint': 'The project is saved to the shared library. Its use in resumes and portfolios is configured separately.',
  'mobileParity.preview': 'Card preview',
  'mobileParity.save': 'Save',
  'mobileParity.unsaved': 'Unsaved changes',
  'mobileParity.saved': 'No unsaved changes',
  'mobileParity.projectSaveError':
      'Unable to save the project. Your input remains in the form; try again.',
  'mobileParity.leaveTitle': 'Unsaved changes',
  'mobileParity.leaveHint': 'Your project changes have not been saved yet.',
  'mobileParity.stay': 'Continue editing',
  'mobileParity.discard': 'Leave without saving',
  'mobileParity.projectNameEmpty': 'Project name',
  'mobileParity.limit': 'Up to {limit} characters',
  'mobileParity.repositoryHint': 'Optional; https:// or http://',
  'mobileParity.demoHint': 'Optional; public demo link',
};
