const russianWorkspaceStrings = <String, String>{
  'nav.resumes': 'Резюме',
  'workspace.all': 'Все',
  'workspace.resume': 'Резюме',
  'workspace.portfolio': 'Портфолио',
  'workspace.createResume': 'Создать резюме',
  'workspace.createPortfolio': 'Создать портфолио',
  'workspace.emptyHome': 'Здесь появятся твои работы',
  'workspace.emptyHomeHint':
      'Создай проект, резюме или портфолио в соответствующем разделе.',
  'workspace.emptyResumes': 'Пока нет резюме',
  'workspace.emptyPortfolios': 'Пока нет портфолио',
  'workspace.emptyDocumentsHint': 'Собери документ из профиля и проектов. Его содержимое можно изменить отдельно.',
  'workspace.draft': 'Черновик',
  'workspace.linkAfterPublish': 'Ссылка появится после публикации',
  'workspace.duplicate': 'Дублировать',
  'workspace.copyTitle': '{title} — копия',
  'workspace.delete': 'Удалить',
  'workspace.deleteTitle': 'Удалить документ?',
  'workspace.deleteHint': 'Профиль, проекты и другие документы останутся. Прикреплённое резюме будет отсоединено от портфолио.',
  'workspace.deleteProjectTitle': 'Удалить проект из библиотеки?',
  'workspace.deleteProjectHint': 'Проект будет удалён из библиотеки и отсоединён от документов. Другие проекты и документы останутся.',
  'workspace.documentLimit': 'Можно сохранить до {count} документов',
  'workspace.legacyTitle': 'Сохранённое портфолио',
  'workspace.legacyResumeTitle': 'Сохранённое резюме',
  'workspace.legacyHint': 'Данные прежнего конструктора сохранены. Перенеси их в отдельные документы, чтобы редактировать их независимо.',
  'workspace.importLegacy': 'Создать документы из прежних данных',
  'workspace.profile': 'Профиль разработчика',
  'workspace.profileHint': 'Эта база предзаполняет новые документы. Уже созданные резюме и портфолио меняются отдельно.',
  'workspace.contactsHint': 'Публичные ссылки для новых документов. Почта для входа не публикуется автоматически.',
  'workspace.openProfile': 'Открыть профиль',
  'workspace.saveProfile': 'Сохранить профиль',
  'workspace.saved': 'Сохранено на устройстве',
  'workspace.modified': 'Изменено {date}',
  'workspace.noDate': 'Дата изменения не сохранена',
  'workspace.failure':
      'Не удалось сохранить. Ввод сохранён в редакторе; попробуй ещё раз.',
};

const englishWorkspaceStrings = <String, String>{
  'nav.resumes': 'Resumes',
  'workspace.all': 'All',
  'workspace.resume': 'Resume',
  'workspace.portfolio': 'Portfolio',
  'workspace.createResume': 'Create resume',
  'workspace.createPortfolio': 'Create portfolio',
  'workspace.emptyHome': 'Your work will appear here',
  'workspace.emptyHomeHint':
      'Create a project, resume or portfolio in its section.',
  'workspace.emptyResumes': 'No resumes yet',
  'workspace.emptyPortfolios': 'No portfolios yet',
  'workspace.emptyDocumentsHint': 'Build a document from your profile and projects, then edit its content independently.',
  'workspace.draft': 'Draft',
  'workspace.linkAfterPublish': 'A link becomes available after publication',
  'workspace.duplicate': 'Duplicate',
  'workspace.copyTitle': '{title} — copy',
  'workspace.delete': 'Delete',
  'workspace.deleteTitle': 'Delete document?',
  'workspace.deleteHint': 'Your profile, projects and other documents stay. An attached resume will be detached from portfolios.',
  'workspace.deleteProjectTitle': 'Delete project from the library?',
  'workspace.deleteProjectHint': 'The project will be removed from the library and detached from documents. Other projects and documents stay.',
  'workspace.documentLimit': 'You can save up to {count} documents',
  'workspace.legacyTitle': 'Saved portfolio',
  'workspace.legacyResumeTitle': 'Saved resume',
  'workspace.legacyHint': 'Your previous builder data is preserved. Convert it into independent documents to edit them separately.',
  'workspace.importLegacy': 'Create documents from previous data',
  'workspace.profile': 'Developer profile',
  'workspace.profileHint': 'This base prefills new documents. Existing resumes and portfolios are edited independently.',
  'workspace.contactsHint': 'Public links for new documents. Your login email is not published automatically.',
  'workspace.openProfile': 'Open profile',
  'workspace.saveProfile': 'Save profile',
  'workspace.saved': 'Saved on this device',
  'workspace.modified': 'Updated {date}',
  'workspace.noDate': 'No saved modification date',
  'workspace.failure':
      'Could not save. Your input stays in the editor; please try again.',
};
